# Generated by Django 5.0.3 on 2025-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educbackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('honors_recieved', models.CharField(max_length=100)),
            ],
        ),
    ]
