# Generated by Django 5.0.3 on 2025-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ_background', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementary_name', models.CharField(max_length=100)),
                ('elementary_address', models.CharField(max_length=100)),
                ('elementary_honors', models.CharField(max_length=100)),
                ('highschool_name', models.CharField(max_length=100)),
                ('highschool_address', models.CharField(max_length=100)),
                ('highschool_honors', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=100)),
                ('college_honors', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Educbackground',
        ),
    ]
